### ISSUE TITLE
bad request

### ISSUE THREAD

**Issue by arteck** [iobroker-community-adapters/ioBroker.webui#139]
![grafik](https://user-images.githubusercontent.com/6681528/147345399-f05ec7fe-723d-4a53-8296-1058fca0d668.png)

wenn ich den klicke 

lande ich hier

`http://localhost:8101/%web_protocol%://localhost:%web_port%/webui/`

**Comment by jogibear9988** [comment]
mhmmm... bei mir ist das nicht so. 
geht es denn wenn die URL eingibst, also 
http://localhost:8101/webui/ ?

**Comment by jogibear9988** [comment]
oder 
http://localhost:8102/webui/
der 81 ist ja admin
