### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by hakarune** [iobroker-community-adapters/ioBroker.webui#143]
tsc not install, had to manually install.

After it still wouldn't start
```
> web-dev-server --node-resolve --open

sh: 1: web-dev-server: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! iobroker.webui@0.0.13 start: `web-dev-server --node-resolve --open`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the iobroker.webui@0.0.13 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

tried to manually install web-dev but received error
```
/usr/bin/webpack-dev-server -> /usr/lib/node_modules/webpack-dev-server/bin/webpack-dev-server.js
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules/webpack-dev-server/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN webpack-dev-server@4.7.4 requires a peer of webpack@^4.37.0 || ^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-dev-middleware@5.3.1 requires a peer of webpack@^4.0.0 || ^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ws@8.5.0 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@8.5.0 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.

+ webpack-dev-server@4.7.4

```

I also tried to fork to use as a docker image, but it received same errors.

**Comment by jogibear9988** [comment]
At the moment, you need to add the "Repo" as a Adapter in iobroker via the Iobroker UI.
But it's only a preview at the moment, hopefully I'll get a full workin Verion in the next 2-3 months

**Comment by hakarune** [comment]
> At the moment, you need to add the "Repo" as a Adapter in iobroker via the Iobroker UI.
> But it's only a preview at the moment, hopefully I'll get a full workin Verion in the next 2-3 months

So I need to add it via iobroker command line in my docker instance? Then do I have to execute these commands without the iobroker docker terminal as well?

**Comment by hakarune** [comment]
tried installing iobroker.web and iobroker.webui and tried running the commands on the readme within the docker as well and it gets stuck at TSC.
```
root@iobroker:/opt/iobroker/ioBroker.webui# npm run tsc

> iobroker.webui@0.0.13 tsc /opt/iobroker/ioBroker.webui
> tsc

sh: 1: tsc: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! iobroker.webui@0.0.13 tsc: `tsc`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the iobroker.webui@0.0.13 tsc script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /opt/iobroker/.npm/_logs/2022-03-18T06_44_57_943Z-debug.log
```

**Comment by jogibear9988** [comment]
the command sin the readme are there, if you download the source in a git directory.
Not if you install it in the iobroker subfolder.

I normaly install the repo in iobroker, and clone the git repo additionaly in a extra directory (for development). In th extra directory you then need to run the commands, and this code in the extra dir then can connect to your iobroker

**Comment by jogibear9988** [comment]
If you only want to test the adapter, you only need to install it via the github URL inside of the adapters page.
You do not need to run any of the steps in the readme

**Comment by jogibear9988** [comment]
Install via the iobroker UI from the github repository, thats the way it should work
