### ISSUE TITLE
Fix releasemanagement

### ISSUE THREAD

**Issue by mcm1957** [iobroker-community-adapters/ioBroker.webui#203]
Releasemanagement should be fixed

- release tags are missing 
- github releases seems to be missing
- README.md contains releasenotes of  0.0.10 although npm provides a 0.0.12
- package.json states a 0.0.20 while io-package.json hspecifies 0.0.15

@alcazone/release-script should be configured and used to avoid inconstiencies

**Comment by jogibear9988** [comment]
I would maybe do this when I think it's ready for a real first use

**Comment by jogibear9988** [comment]
is now included and will be used on first release

**Comment by mcm1957** [comment]
thanks
