### ISSUE TITLE
Please fix issues reported by adapter checker

### ISSUE THREAD

**Issue by mcm1957** [iobroker-community-adapters/ioBroker.webui#204]
[E118] Versions in package.json and in io-package.json are different
[E145] No "common.news" found for actual version 0.0.15
[E500] node_modules found in repo. Please delete it
[E606] Current adapter version 0.0.20 not found in README.md
[E605] No actual year found in copyright. Please add "Copyright (c) 2023 jochen.kuehner@gmx.de" at the end of README.md
[E701] No actual year found in LICENSE. Please add "Copyright (c) 2023 jochen.kuehner@gmx.de" at the start of LICENSE
[E812] file test/ found in repository, but not found in .npmignore
[E813] file src/ found in repository, but not found in .npmignore
[W171] "common.title" is deprecated in io-package.json
[W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
[W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
[W164] Adapters without config "common.noConfig = true" should also set "common.adminUI.config = none"
[W172] "common.localLink" in io-package.json is deprecated. Please define object "common.localLinks": { "_default": "..." }
[W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
[W202] Version of package.json (0.0.20) doesn't match latest version on NPM (0.0.12)
[W400] Cannot find "webui" in latest repository
 

<br class="Apple-interchange-newline">
</body>
</html>

**Comment by jogibear9988** [comment]
most are fixed, some could not be fixed

e.g.:
[E500] node_modules found in repo. Please delete it

they are needed, without adapter is not installable via github (this is special on web adapters)
