### ISSUE TITLE
Unable to install packages

### ISSUE THREAD

**Issue by hrglzpf** [iobroker-community-adapters/ioBroker.webui#258]
When I double click on a package in suggestions, the footer bar shows that npm (tries?) installs the package.
In iobroker I can see, that the instance of webui is stopped and in the host section I get the error message "Exception-Code: ENOENT: spawn npm ENOENT" and "Issues with non-existing files or directories" "A process tries to access a non-existing file or directory."

**Comment by hrglzpf** [comment]
Log output
![image](https://github.com/iobroker-community-adapters/ioBroker.webui/assets/40138650/7548523e-1b67-4ad6-8673-dee7ef3072ef)

**Comment by jogibear9988** [comment]
sorry I have not seen this issue until now, but I can not reproduce.
I've tried in a fresh ioBroker installation and it worked.

**Comment by hrglzpf** [comment]
Here some config info

Webui: v0.14.1
platform: Windows 11
Node.js: v20.9.0
NPM: 10.2.3
js-controller: 5.0.16
Path: C:\ioBroker\

**Comment by hrglzpf** [comment]
So what I understand from your reply, it looks like it´s a "local" issue
The issue is, that webui (or NPM?) tries to access a non-existing director or file
Which directories and / or files are accessed?
Then I would check the permissions - could be an easy fix

And: no apologies, you doing this in your free time

**Comment by jogibear9988** [comment]
maybe it's a windows issue... i never tried webui on a windows machine.

**Comment by jogibear9988** [comment]
I'll look what I can do. Maybe I'll try to install on my windows machine at work tomorrow

**Comment by jogibear9988** [comment]
I could reproduce in windows, happens also to me. I'll look tomorrow

**Comment by hrglzpf** [comment]
Works now.
Thanks
