### ISSUE TITLE
Aufruf "edit complex value" über eigenen Button

### ISSUE THREAD

**Issue by Blockmove** [iobroker-community-adapters/ioBroker.webui#269]
Der Aufruf von "edit complex value"  sollte über einen eigenen Button anstelle des Linksclicks auf den Text "value" erfolgen.
So ist die Funktion - meiner Meinung nach - zu versteckt.

**Comment by jogibear9988** [comment]
Zur Info: Hier ist der Rechtsklick in Simple-Script Scripten gemeint

**Comment by jogibear9988** [comment]
fix in develop
