### ISSUE TITLE
Installed packages not shown in Firefox

### ISSUE THREAD

**Issue by Medel** [iobroker-community-adapters/ioBroker.webui#290]
webui version: 1.0.37
Firefox: 115.7.0esr

After install and reload no installed packages shown under Controls->Designer
Chome browser works

**Comment by jogibear9988** [comment]
Could you show messges from your firefox console (Press F12 to enter developer Tools)
Could you try a newer firefox? (I have 122 and it works)

**Comment by Medel** [comment]
I installed Firefox 122.0 (64-Bit) and it works.
