### ISSUE TITLE
webui Custom Control get Property Changes in javascript

### ISSUE THREAD

**Issue by gokturk413** [iobroker-community-adapters/ioBroker.webui#291]
How to do webui Custom Control get Property Changes in javascript.for example i have levelbar custom controls? i bind levelbar div height  to my property level and  i want to get updates in custom controls and other properties? How to do subscribe properties changes

**Comment by jogibear9988** [comment]
Do you mean how you can listen to changes of properties you have defined in the properties list below? If this is the case there are few ways.
(When I'm thinking now, I should add an direct way from there to link to a named javascript function in the JS code, I will add this)

1.) You could use the property in a binding. You could access the value via "??propertyname" in the binding. This is usable if you could bind the property directly to a css value, innerHtml,...

2.) you could register a eventListener in the connectedCallback. The eventlistener is always the propertyname + -changed
if you use the _assignEvent helper, it removes the listener automatically in the disconnectedCallback and adds it again in the connectedCallback.
The "init" is called once for each instance of the element created.

          /**
          * @param {BaseScreenViewerAndControl} instance
          */
          export function init(instance) {
              instance._assignEvent('propertyname-changed', () => ....);
          }

**Comment by gokturk413** [comment]
i check it already  it does not fire event. I craete level property and add
export function init(instance) {
          instance._assignEvent('level-changed', () => console.log('whatis'));
      }

**Comment by gokturk413** [comment]
Thank you.It works
