### ISSUE TITLE
Runtime does not work

### ISSUE THREAD

**Issue by shadowbit21** [iobroker-community-adapters/ioBroker.webui#312]
<img width="1437" alt="Bildschirmfoto 2024-05-12 um 10 33 52" src="https://github.com/iobroker-community-adapters/ioBroker.webui/assets/167664403/49bd4c2b-77a3-4156-88ab-a6b74c58cb01">

**Comment by jogibear9988** [comment]
wich version? what npms have you installed?

**Comment by shadowbit21** [comment]
Version 1.6.5Von meinem iPhone gesendetAm 12.05.2024 um 13:49 schrieb Jochen Kühner ***@***.***>:﻿
wich version? what npms have you installed?

**Comment by jogibear9988** [comment]
Du you have created a screen called „main“?Von meinem iPhone gesendetAm 12.05.2024 um 11:05 schrieb shadowbit21 ***@***.***>:﻿
Version 1.6.5Von meinem iPhone gesendetAm 12.05.2024 um 13:49 schrieb Jochen Kühner ***@***.***>:﻿

wich version? what npms have you installed?

**Comment by jogibear9988** [comment]
Wich url do you use?

**Comment by jogibear9988** [comment]
Wich url do you use?Von meinem iPhone gesendetAm 12.05.2024 um 11:23 schrieb Jochen Kühner ***@***.***>:﻿Du you have created a screen called „main“?Von meinem iPhone gesendetAm 12.05.2024 um 11:05 schrieb shadowbit21 ***@***.***>:﻿
Version 1.6.5Von meinem iPhone gesendetAm 12.05.2024 um 13:49 schrieb Jochen Kühner ***@***.***>:﻿

wich version? what npms have you installed?

**Comment by jogibear9988** [comment]
And have you installed additional packages?

**Comment by shadowbit21** [comment]
Es funktioniert jetzt. Aber früher gab tatsächlich das  Problem, dass runtime nicht gestartet wurde. Warum es jetzt  funktioniert, weiß ich nicht oder warum es damals nicht funktioniert hat, weiß ich auch nicht.  Es ist irritierend, dass beim Start vom Editor keine einzige Seite geöffnet wird und man muss erst mal suchen, wo man überhaupt eine Seite aufmacht. Wenn man den Editor schließt, geht man eigentlich davon aus, dass beim nächstes Mal gleiche Einstellungen und das gleiche Fenster sichtbar sind. Das ist aber nicht so. LGAm 12.05.2024 um 17:24 schrieb Jochen Kühner ***@***.***>:﻿
And have you installed additional packages?
