### ISSUE TITLE
SetElementProperty Toggle Class not working

### ISSUE THREAD

**Issue by th3112** [iobroker-community-adapters/ioBroker.webui#384]
**Webui version**
1.19.4

**Describe the bug**
Hi,
I have just updated from 1.15.x to 19.1.4. Since then I have the problem that SetElementProperty command seems to not work any more.

I have a button that should toggle a class "open" for a sidebar. In the old version 1.15. it works as expected but with the new one it is no longer working. Error can be reproduced. After re-installing 1.15 it works again.

The button is configure as shown in the screenshot
<img width="454" alt="webui-error" src="https://github.com/user-attachments/assets/48723bbe-5663-4763-bea8-7148776fb41a">

Br
Thomas

**Comment by jogibear9988** [comment]
Should work in Version 1.20.1
look at: http://129.159.205.3:8082/webui/index.html
screen: classtoggle

**Comment by th3112** [comment]
Sorry, seems not to work with 1.20.1. I have installed it and see the same issue than with 1.19.4
I put my example at http://129.159.205.3:8082/webui/index.html in the folder issue_384.

**Comment by th3112** [comment]
Start with the screen "StartThis". The Menu button does not add class "open" to Element sidebar.

**Comment by th3112** [comment]
The same issue occurs for the Element overlay. This element is used to close the sidebar if the user clicks somewhere out of the menu.

As I said there is no problem with 1.15.4

**Comment by jogibear9988** [comment]
2 Problems, 

<img width="399" alt="image" src="https://github.com/user-attachments/assets/d79c6903-2c02-4a64-9735-8ed02cc0a5aa">

target needs to be container, and "name" needs to be empty, at the moment it is a emoty string. I will fix that it works with an empty string, but it's not yet released.

can you copy the source of the binding of version 1.15, so I see why it does not work...

**Comment by th3112** [comment]
Hi,
the source is exactly that what I am using in 1.15.1 I just exported it and re-Import it on the sample Server

thank you very much for your support

**Comment by jogibear9988** [comment]
so it's fixed now?
